<a href="https://colab.research.google.com/github/adhyapratheesh/house_price_prediction/blob/main/Peoject4_Movie_Recommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import difflib
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
movie_data=pd.read_csv("/content/movie.csv")

In [ ]:
movie_data.head()

index     budget                                    genres  \
0      0  237000000  Action Adventure Fantasy Science Fiction   
1      1  300000000                  Adventure Fantasy Action   
2      2  245000000                    Action Adventure Crime   
3      3  250000000               Action Crime Drama Thriller   
4      4  260000000          Action Adventure Science Fiction   

                                       homepage      id  \
0                   http://www.avatarmovie.com/   19995   
1  http://disney.go.com/disneypictures/pirates/     285   
2   http://www.sonypictures.com/movies/spectre/  206647   
3            http://www.thedarkknightrises.com/   49026   
4          http://movies.disney.com/john-carter   49529   

                                            keywords original_language  \
0  culture clash future space war space colony so...                en   
1  ocean drug abuse exotic island east india trad...                en   
2         spy based on novel secret agent sequel mi6                en   
3  dc comics crime fighter terrorist secret ident...                en   
4  based on novel mars medallion space travel pri...                en   

                             original_title  \
0                                    Avatar   
1  Pirates of the Caribbean: At World's End   
2                                   Spectre   
3                     The Dark Knight Rises   
4                               John Carter   

                                            overview  popularity  ... runtime  \
0  In the 22nd century, a paraplegic Marine is di...  150.437577  ...   162.0   
1  Captain Barbossa, long believed to be dead, ha...  139.082615  ...   169.0   
2  A cryptic message from Bond’s past sends him o...  107.376788  ...   148.0   
3  Following the death of District Attorney Harve...  112.312950  ...   165.0   
4  John Carter is a war-weary, former military ca...   43.926995  ...   132.0   

                                    spoken_languages    status  \
0  [{"iso_639_1": "en", "name": "English"}, {"iso...  Released   
1           [{"iso_639_1": "en", "name": "English"}]  Released   
2  [{"iso_639_1": "fr", "name": "Fran\u00e7ais"},...  Released   
3           [{"iso_639_1": "en", "name": "English"}]  Released   
4           [{"iso_639_1": "en", "name": "English"}]  Released   

                                          tagline  \
0                     Enter the World of Pandora.   
1  At the end of the world, the adventure begins.   
2                           A Plan No One Escapes   
3                                 The Legend Ends   
4            Lost in our world, found in another.   

                                      title vote_average vote_count  \
0                                    Avatar          7.2      11800   
1  Pirates of the Caribbean: At World's End          6.9       4500   
2                                   Spectre          6.3       4466   
3                     The Dark Knight Rises          7.6       9106   
4                               John Carter          6.1       2124   

                                                cast  \
0  Sam Worthington Zoe Saldana Sigourney Weaver S...   
1  Johnny Depp Orlando Bloom Keira Knightley Stel...   
2  Daniel Craig Christoph Waltz L\u00e9a Seydoux ...   
3  Christian Bale Michael Caine Gary Oldman Anne ...   
4  Taylor Kitsch Lynn Collins Samantha Morton Wil...   

                                                crew           director  
0  [{'name': 'Stephen E. Rivkin', 'gender': 0, 'd...      James Cameron  
1  [{'name': 'Dariusz Wolski', 'gender': 2, 'depa...     Gore Verbinski  
2  [{'name': 'Thomas Newman', 'gender': 2, 'depar...         Sam Mendes  
3  [{'name': 'Hans Zimmer', 'gender': 2, 'departm...  Christopher Nolan  
4  [{'name': 'Andrew Stanton', 'gender': 2, 'depa...     Andrew Stanton  

[5 rows x 24 columns]

In [ ]:
movie_data.shape

(4803, 24)

In [ ]:
selected_features=['genres','keywords','tagline','overview','cast','director']

In [ ]:
for feature in selected_features:
  movie_data[feature]=movie_data[feature].fillna('')

In [ ]:
combine_features=movie_data['genres']+" "+movie_data['keywords']+" "+movie_data['tagline']+" "+movie_data['overview']+" "+movie_data['cast']+" "+movie_data['director']

In [ ]:
print(combine_features)

0       Action Adventure Fantasy Science Fiction cultu...
1       Adventure Fantasy Action ocean drug abuse exot...
2       Action Adventure Crime spy based on novel secr...
3       Action Crime Drama Thriller dc comics crime fi...
4       Action Adventure Science Fiction based on nove...
                              ...                        
4798    Action Crime Thriller united states\u2013mexic...
4799    Comedy Romance  A newlywed couple's honeymoon ...
4800    Comedy Drama Romance TV Movie date love at fir...
4801      A New Yorker in Shanghai When ambitious New ...
4802    Documentary obsession camcorder crush dream gi...
Length: 4803, dtype: object


In [ ]:
vectorizer=TfidfVectorizer()

In [ ]:
feature_vectors=vectorizer.fit_transform(combine_features)

In [ ]:
print(feature_vectors)

  (0, 4288)	0.13213124585063998
  (0, 14180)	0.08418056281586365
  (0, 23134)	0.14987864628095252
  (0, 17784)	0.12285843797047788
  (0, 15569)	0.17136669159262102
  (0, 25868)	0.11590870590502834
  (0, 29614)	0.15064979633862854
  (0, 24802)	0.15892578492394402
  (0, 23578)	0.16802034155542867
  (0, 30543)	0.15064979633862854
  (0, 30145)	0.18243919685121027
  (0, 23619)	0.11047375838269541
  (0, 5245)	0.16506865163441017
  (0, 1014)	0.12285843797047788
  (0, 1243)	0.05270709034262742
  (0, 21523)	0.16650106431669984
  (0, 1281)	0.0319519027005067
  (0, 19650)	0.16120557402371172
  (0, 10368)	0.138482776543016
  (0, 2974)	0.09974129089792808
  (0, 27515)	0.1456922041909068
  (0, 2685)	0.09805341831299118
  (0, 4129)	0.06195738171764886
  (0, 18025)	0.1093940665047336
  (0, 28597)	0.15490753406550084
  :	:
  (4802, 27153)	0.05940079357098276
  (4802, 19243)	0.061349419053434766
  (4802, 11941)	0.07829183421073846
  (4802, 29680)	0.07735547381237222
  (4802, 9346)	0.07104321122746965
  

In [ ]:
similarity=cosine_similarity(feature_vectors)

In [ ]:
print(similarity)

[[1.         0.05083168 0.0332947  ... 0.02749812 0.0304889  0.0072518 ]
 [0.05083168 1.         0.04356836 ... 0.05077045 0.03100979 0.01521198]
 [0.0332947  0.04356836 1.         ... 0.02646984 0.04751623 0.01372603]
 ...
 [0.02749812 0.05077045 0.02646984 ... 1.         0.03481447 0.03546821]
 [0.0304889  0.03100979 0.04751623 ... 0.03481447 1.         0.03098945]
 [0.0072518  0.01521198 0.01372603 ... 0.03546821 0.03098945 1.        ]]


In [ ]:
similarity.shape

(4803, 4803)

In [ ]:
movie_name=input("Enter the movie name:")

Enter the movie name:avatar


In [ ]:
all_titles=movie_data['title'].tolist()

In [ ]:
find_close_one=difflib.get_close_matches(movie_name,all_titles)
print(find_close_one)

['Avatar']


In [ ]:
close_match=find_close_one[0]
print(close_match)

Avatar


In [ ]:
index_movie=movie_data[movie_data.title==close_match]['index'].values[0]
print(index_movie)

0


In [ ]:
similarity_score=list(enumerate(similarity[index_movie]))
print(similarity_score)

[(0, 1.0), (1, 0.050831680232069756), (2, 0.03329469936108887), (3, 0.034800715550373715), (4, 0.08724686630893659), (5, 0.0566969483263915), (6, 0.022512258494852985), (7, 0.067737097155122), (8, 0.021355368766540136), (9, 0.03335541241190939), (10, 0.05173124937993882), (11, 0.03550752960409978), (12, 0.02240876024461901), (13, 0.029840631369536706), (14, 0.06234629311654262), (15, 0.034860087588110183), (16, 0.04270511084643852), (17, 0.033016644150653994), (18, 0.0623433305067024), (19, 0.03758892805682068), (20, 0.03241544693179115), (21, 0.022573109365739856), (22, 0.023383368657539153), (23, 0.03815117320234564), (24, 0.02806546556566892), (25, 0.03954093319213126), (26, 0.07744606074605177), (27, 0.09086096153920839), (28, 0.028921214453158275), (29, 0.05215792057595854), (30, 0.04679198413957891), (31, 0.0736943901746957), (32, 0.044169525398501275), (33, 0.03254398014655571), (34, 0.018228986764685536), (35, 0.05868616002771497), (36, 0.08506438514870908), (37, 0.059348380107

In [ ]:
sorted_movie_list=sorted(similarity_score,key = lambda x :x[1],reverse=True)
print(sorted_movie_list)

[(0, 1.0), (1914, 0.16126755021560363), (1531, 0.15947661416113426), (3158, 0.1535358004049935), (56, 0.15169213117081484), (1352, 0.14938085657201705), (2403, 0.14835180763632996), (94, 0.14151403414407035), (239, 0.13355702242870096), (2198, 0.13162057575067118), (3604, 0.1292826180046452), (461, 0.12876702330020762), (3730, 0.1269519487017688), (369, 0.12601494004493408), (305, 0.1243202815065048), (342, 0.12374180568725782), (47, 0.12367872604116283), (661, 0.12296563604922991), (942, 0.12234596060863662), (1275, 0.12224354634574001), (150, 0.11975427140900297), (1354, 0.11884216977680725), (4401, 0.11831843195930059), (300, 0.11678308373871141), (432, 0.11587675428201624), (529, 0.11423470366536424), (1759, 0.11402805386153815), (549, 0.11354716615947663), (43, 0.11324250877132759), (2995, 0.11218183545630808), (311, 0.11160871159754025), (4332, 0.11149904057704481), (2696, 0.1110926569102497), (4593, 0.11014673956791822), (1053, 0.10989684187615312), (775, 0.10901058437260237), (

In [ ]:
print("Movie suggestions are :")
i=1;
for movie in sorted_movie_list[1:]:
  index=movie[0]
  movie_names=movie_data[movie_data.index==index]["title"].values[0]
  if i<20:
    print(i,".",movie_names)
    i=i+1



Movie suggestions are :
1 . Lifeforce
2 . Moonraker
3 . Alien
4 . Star Trek Beyond
5 . Gattaca
6 . Aliens
7 . Guardians of the Galaxy
8 . Gravity
9 . Lockout
10 . Apollo 18
11 . Lost in Space
12 . Cargo
13 . Lara Croft Tomb Raider: The Cradle of Life
14 . Treasure Planet
15 . Men in Black
16 . Star Trek Into Darkness
17 . Zathura: A Space Adventure
18 . The Book of Life
19 . Sunshine


MOVIE RECOMMENDATION SYSYTEM

In [45]:
movie_name=input("Enter the movie name :")
all_titles=movie_data['title'].tolist()
find_close_one=difflib.get_close_matches(movie_name,all_titles)
close_match=find_close_one[0]
index_movie=movie_data[movie_data.title==close_match]['index'].values[0]
similarity_score=list(enumerate(similarity[index_movie]))
sorted_movie_list=sorted(similarity_score,key = lambda x :x[1],reverse=True)
print("Movie suggestions are :")
i=1;
for movie in sorted_movie_list[1:]:
  index=movie[0]
  movie_names=movie_data[movie_data.index==index]["title"].values[0]
  if i<=20:
    print(i,".",movie_names)
    i=i+1


Enter the movie name :iron man
Movie suggestions are :
1 . Iron Man 2
2 . Iron Man 3
3 . Avengers: Age of Ultron
4 . The Avengers
5 . X-Men
6 . The Helix... Loaded
7 . Captain America: Civil War
8 . X-Men: Apocalypse
9 . Ant-Man
10 . Made
11 . Guardians of the Galaxy
12 . X-Men: Days of Future Past
13 . Super
14 . Mortdecai
15 . The Incredible Hulk
16 . Mystery Men
17 . Captain America: The Winter Soldier
18 . The Devil's Tomb
19 . X-Men: First Class
20 . Kick-Ass 2
